# State Machine Configuration Template
role:
  name: wonderland_restaurant_guide
# Define the states of the state machine
states:
  - name: initial
    state_type: start
    transitions:
      - to: information_collection
        priority: 1

  - name: information_collection
    state_type: action
    event_actions:
      collect_info:
        - name: collect_information
    transitions:
      - to: restaurant_recommendation
        priority: 1
        condition: collect_info

  - name: restaurant_recommendation
    state_type: action
    event_actions:
      make_recommendation:
        - name: generate_recommendation
      modify_preferences:
        - name: transit_to_information_collection
      default_fallback_event:
        - name: gently_ask_for_relevant_information
    transitions:
      - to: restaurant_detail_retrieval
        condition: make_recommendation
        priority: 1
      - to: information_collection
        condition: modify_preferences
        priority: 2
      - to: error
        condition: recommendation_failed
        priority: 0

  - name: restaurant_detail_retrieval
    state_type: action
    transitions:
      - to: information_collection
        condition: request_to_update_filter_criteria
        priority: 2
      - to: success
        condition: details_retrieved
        priority: 1
      - to: error
        condition: retrieval_failed
        priority: 0

  - name: success
    state_type: end

  - name: error
    state_type: end

# Define properties for each state
properties:
  initial:
    description: "The start state where the process begins."
  information_collection:
    description: "Collecting information from the user."
  ask_geo_location:
    description: "Asking the user for their geographical location."
  ask_credit_card_type_issuer:
    description: "Asking the user for their credit card type and issuer."
  ask_price_range:
    description: "Asking the user about their preferred price range."
  ask_rating_range:
    description: "Asking the user about their preferred restaurant rating."
  restaurant_recommendation:
    description: "Recommending a restaurant based on collected information."
  restaurant_detail_retrieval:
    description: "Retrieving details of the recommended restaurant."
  gently_ask_for_relevant_information:
    description: "Gently asking the user for relevant information."
  success:
    description: "End state indicating a successful process."
  error:
    description: "End state indicating an error occurred."
  collect_info:
    description: "Target is trying to find a restaurant"
  make_recommendation:
    description: "Asking for restaurant recommendations"
  modify_preferences:
    description: "Target want to change the restaurant preferences"
  default_fallback_event:
    description: "Target is not trying to find a restaurant"
