prompt: |
  Agent Name: {agent_name}
  Agent Description: {agent_description}
  Agent Current state: {current_state}
  Request from target: {raw_query}
  Event list:
    {event_list}

  Task: Based on the target's request return one from the event list; if the request is not related with event then return default_fallback_event; event name only

type: generic

parameters:
  agent_name:
    description: Name of the agent
    type: str
  agent_description:
    description: Description of the agent
    type: str
  agent_goal:
    description: Goal of the agent
    type: str
  current_state:
    description: Current state of the agent
    type: str
  raw_query:
    description: Raw query from the target
    type: str
  event_list:
    description: List of possible events
    type: str
